import { useEffect, useMemo, useRef, useState, type CSSProperties, type DragEvent, type PointerEvent } from 'react';
import { listen } from '@tauri-apps/api/event';
import { api, AppError } from '../../lib/tauri';
import type { ConnectionDto, FileEntry, LocalFileEntry, ServerProfile, TransferJob } from '../../types/contracts';

interface Props { server: ServerProfile; connection: ConnectionDto; peers: Array<{ server: ServerProfile; connection: ConnectionDto }>; onNotify: (message: string) => void; onError: (message: string) => void; }
type DragPayload = { side: 'local'; entry: LocalFileEntry } | { side: 'remote'; entry: FileEntry };
type PendingTransfer = { kind: 'upload' | 'download'; localPath: string; remotePath: string } | { kind: 'serverToServer'; sourceServerId: string; sourceConnectionId: string; sourcePath: string; destServerId: string; destConnectionId: string; destPath: string };
type CopyDraft = { source: FileEntry; peerId: string; destPath: string };
const DRAG_TYPE = 'application/x-infradeck-file';
const errorText = (cause: unknown) => cause instanceof AppError ? `${cause.dto.code}: ${cause.message}` : String(cause);
const remoteJoin = (base: string, name: string) => `${base === '/' ? '' : base}/${name}`;
const localJoin = (base: string, name: string) => `${base.replace(/[\\/]$/, '')}${base.includes('\\') ? '\\' : '/'}${name}`;
const basename = (path: string) => path.split(/[\\/]/).filter(Boolean).slice(-1)[0] ?? path;
const parentPath = (path: string, remote = false) => remote ? (path === '/' ? '/' : path.replace(/\/?[^/]+\/?$/, '') || '/') : (() => { const value = path.replace(/[\\/]$/, ''); const index = Math.max(value.lastIndexOf('\\'), value.lastIndexOf('/')); return index <= 2 ? value.slice(0, index + 1) : value.slice(0, index); })();
const formatSize = (bytes: number) => bytes === 0 ? '0 B' : bytes >= 1 << 30 ? `${(bytes / (1 << 30)).toFixed(1)} GiB` : bytes >= 1 << 20 ? `${(bytes / (1 << 20)).toFixed(1)} MiB` : bytes >= 1 << 10 ? `${(bytes / (1 << 10)).toFixed(1)} KiB` : `${bytes} B`;
const formatDate = (value?: string) => { if (!value) return '—'; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString(undefined, { dateStyle: 'short', timeStyle: 'short' }); };
const formatSpeed = (bytes?: number) => !bytes ? '—' : bytes >= 1 << 20 ? `${(bytes / (1 << 20)).toFixed(1)} MB/s` : `${Math.max(1, Math.round(bytes / 1024))} KB/s`;
const stateLabel = (state: TransferJob['state']) => ({ queued: '排队中', running: '传输中', paused: '已暂停', completed: '已完成', failed: '失败', cancelled: '已取消' })[state];
const formatEta = (job: TransferJob) => { if (!job.speedBytesPerSec || job.state !== 'running') return '—'; const seconds = Math.ceil(Math.max(0, job.totalBytes - job.transferredBytes) / job.speedBytesPerSec); return seconds < 60 ? `约 ${seconds} 秒` : `约 ${Math.ceil(seconds / 60)} 分钟`; };

export default function FilesView({ server, connection, peers, onNotify, onError }: Props) {
  const [remotePath, setRemotePath] = useState('/');
  const [remoteEntries, setRemoteEntries] = useState<FileEntry[]>([]);
  const [remoteError, setRemoteError] = useState<string>();
  const [localPath, setLocalPath] = useState('');
  const [localEntries, setLocalEntries] = useState<LocalFileEntry[]>([]);
  const [localError, setLocalError] = useState<string>();
  const [localLoading, setLocalLoading] = useState(false);
  const [remoteLoading, setRemoteLoading] = useState(false);
  const [transfers, setTransfers] = useState<TransferJob[]>([]);
  const [queueFilter, setQueueFilter] = useState<'active' | 'completed' | 'failed'>('active');
  const [queueCollapsed, setQueueCollapsed] = useState(false);
  const [selected, setSelected] = useState<{ side: 'local' | 'remote'; path: string }>();
  const [selectedPaths, setSelectedPaths] = useState<{ local: string[]; remote: string[] }>({ local: [], remote: [] });
  const [localPanePercent, setLocalPanePercent] = useState(50);
  const [conflict, setConflict] = useState<PendingTransfer>();
  const [copyDraft, setCopyDraft] = useState<CopyDraft>();
  const [errorDetailId, setErrorDetailId] = useState<string>();
  const [dropSide, setDropSide] = useState<'local' | 'remote'>();
  const [pathEditor, setPathEditor] = useState<{ side: 'local' | 'remote'; value: string }>();
  const [directoryName, setDirectoryName] = useState<string>();
  const [deleteTarget, setDeleteTarget] = useState<FileEntry>();
  const localPathRef = useRef(localPath);
  const remotePathRef = useRef(remotePath);
  localPathRef.current = localPath; remotePathRef.current = remotePath;

  const loadRemote = async (path: string) => { setRemoteLoading(true); setRemoteError(undefined); try { setRemoteEntries(await api.fsList(connection.id, path)); setRemotePath(path); } catch (cause) { const message = errorText(cause); setRemoteEntries([]); setRemoteError(message); onError(message); } finally { setRemoteLoading(false); } };
  const loadLocal = async (path?: string) => { setLocalLoading(true); setLocalError(undefined); try { const target = path || localPath || await api.localFsHome(); setLocalEntries(await api.localFsList(target)); setLocalPath(target); } catch (cause) { const message = errorText(cause); setLocalEntries([]); setLocalError(message); onError(message); } finally { setLocalLoading(false); } };
  const refreshTransfers = async () => { try { setTransfers(await api.fsTransfersList()); } catch { /* best effort */ } };
  useEffect(() => { void loadRemote('/'); void loadLocal(); void refreshTransfers(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [connection.id]);
  useEffect(() => { const timer = window.setInterval(() => void refreshTransfers(), 3500); return () => window.clearInterval(timer); }, []);
  useEffect(() => {
    let disposed = false; const off: Array<() => void> = [];
    const register = async <T,>(event: string, handler: (event: { payload: T }) => void) => { const unlisten = await listen<T>(event, handler); if (disposed) unlisten(); else off.push(unlisten); };
    void register<TransferJob>('transfer.progress', ({ payload }) => setTransfers((items) => items.map((job) => job.transferId === payload.transferId ? { ...job, transferredBytes: payload.transferredBytes, speedBytesPerSec: payload.speedBytesPerSec } : job)));
    void register<TransferJob>('transfer.finished', ({ payload }) => { setTransfers((items) => items.map((job) => job.transferId === payload.transferId ? payload : job)); void loadRemote(remotePathRef.current); void loadLocal(localPathRef.current); });
    void register<{ transferId: string; state: TransferJob['state'] }>('transfer.state', ({ payload }) => setTransfers((items) => items.map((job) => job.transferId === payload.transferId ? { ...job, state: payload.state } : job)));
    return () => { disposed = true; off.splice(0).forEach((fn) => fn()); };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [connection.id]);

  const startTransfer = async (kind: 'upload' | 'download', localPath: string, remotePath: string, overwrite = false): Promise<'started' | 'conflict' | 'failed'> => {
    try { const job = await api.fsTransferStart({ kind, serverId: server.id, connectionId: connection.id, localPath, remotePath, overwrite }); setTransfers((items) => [...items.filter((item) => item.transferId !== job.transferId), job]); setQueueFilter('active'); setQueueCollapsed(false); onNotify(kind === 'upload' ? '上传已开始。' : '下载已开始。'); return 'started'; }
    catch (cause) { if (cause instanceof AppError && cause.dto.code === 'FS_EXISTS') { setConflict({ kind, localPath, remotePath }); return 'conflict'; } onError(errorText(cause)); return 'failed'; }
  };
  const startServerCopy = async (request: Extract<PendingTransfer, { kind: 'serverToServer' }>, overwrite = false) => {
    try { const job = await api.ss2sTransferStart({ sourceServerId: request.sourceServerId, sourceConnectionId: request.sourceConnectionId, sourcePath: request.sourcePath, destServerId: request.destServerId, destConnectionId: request.destConnectionId, destPath: request.destPath, overwrite }); setTransfers((items) => [...items.filter((item) => item.transferId !== job.transferId), job]); setQueueFilter('active'); setQueueCollapsed(false); onNotify('跨服务器复制已开始。'); }
    catch (cause) { if (cause instanceof AppError && cause.dto.code === 'SS2S_DEST_EXISTS') { setConflict(request); return; } onError(errorText(cause)); }
  };
  const resolveConflict = (overwrite: boolean) => { if (!conflict) return; const pending = conflict; setConflict(undefined); if (pending.kind === 'serverToServer') void startServerCopy(pending, overwrite); else void startTransfer(pending.kind, pending.localPath, pending.remotePath, overwrite); };
  const retry = (job: TransferJob) => { if (job.kind === 'serverToServer' && job.sourceServerId && job.sourceConnectionId && job.sourcePath) void startServerCopy({ kind: 'serverToServer', sourceServerId: job.sourceServerId, sourceConnectionId: job.sourceConnectionId, sourcePath: job.sourcePath, destServerId: job.serverId, destConnectionId: job.connectionId, destPath: job.remotePath }); else if (job.kind === 'upload' || job.kind === 'download') void startTransfer(job.kind, job.localPath, job.remotePath); };
  const toggleSelection = (side: 'local' | 'remote', path: string, checked: boolean) => { setSelectedPaths((items) => ({ ...items, [side]: checked ? [...new Set([...items[side], path])] : items[side].filter((item) => item !== path) })); if (checked) setSelected({ side, path }); };
  const startBatch = async (kind: 'upload' | 'download', entries: Array<LocalFileEntry | FileEntry>) => { const active = transfers.filter((job) => job.connectionId === connection.id && ['queued', 'running', 'paused'].includes(job.state)).length; const capacity = Math.max(0, 2 - active); if (!capacity) { onError('当前服务器已有 2 个传输任务，请等待任务完成后再继续。'); return; } const batch = entries.slice(0, capacity); for (const entry of batch) { const outcome = kind === 'upload' ? await startTransfer('upload', entry.path, remoteJoin(remotePath, entry.name)) : await startTransfer('download', localJoin(localPath, entry.name), entry.path); if (outcome !== 'started') break; } if (entries.length > capacity) onNotify(`已按当前并发上限启动前 ${capacity} 项；其余文件请在任务完成后继续传输。`); };
  const clearFinished = async () => { try { const removed = await api.fsTransfersClearFinished(connection.id); setTransfers((items) => items.filter((item) => !(item.connectionId === connection.id || item.sourceConnectionId === connection.id) || !['completed', 'failed', 'cancelled'].includes(item.state))); onNotify(removed ? `已清除 ${removed} 个已结束任务。` : '没有可清除的已结束任务。'); } catch (cause) { onError(errorText(cause)); } };
  const getPayload = (event: DragEvent): DragPayload | undefined => { try { return JSON.parse(event.dataTransfer.getData(DRAG_TYPE)) as DragPayload; } catch { return undefined; } };
  const beginDrag = (event: DragEvent, payload: DragPayload) => { if (payload.entry.kind !== 'file') { event.preventDefault(); return; } event.dataTransfer.effectAllowed = 'copy'; event.dataTransfer.setData(DRAG_TYPE, JSON.stringify(payload)); };
  const dropRemote = (event: DragEvent, directory = remotePath) => { event.preventDefault(); const payload = getPayload(event); if (payload?.side === 'local' && payload.entry.kind === 'file') void startTransfer('upload', payload.entry.path, remoteJoin(directory, payload.entry.name)); };
  const dropLocal = (event: DragEvent, directory = localPath) => { event.preventDefault(); const payload = getPayload(event); if (payload?.side === 'remote' && payload.entry.kind === 'file') void startTransfer('download', localJoin(directory, payload.entry.name), payload.entry.path); };
  const resizePanes = (event: PointerEvent<HTMLDivElement>) => { const container = event.currentTarget.parentElement; if (!container) return; const rect = container.getBoundingClientRect(); const move = (pointer: globalThis.PointerEvent) => setLocalPanePercent(Math.min(72, Math.max(28, (pointer.clientX - rect.left) / rect.width * 100))); const stop = () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', stop); }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', stop); };
  const mkdir = async () => { const name = directoryName?.trim(); if (!name) return; try { await api.fsMkdir(connection.id, server.id, remoteJoin(remotePath, name)); setDirectoryName(undefined); await loadRemote(remotePath); } catch (cause) { onError(errorText(cause)); } };
  const removeRemote = async () => { if (!deleteTarget) return; try { await api.fsDelete(connection.id, server.id, deleteTarget.path, deleteTarget.kind === 'directory'); setDeleteTarget(undefined); await loadRemote(remotePath); } catch (cause) { onError(errorText(cause)); } };
  const savePath = () => { if (!pathEditor?.value.trim()) return; const target = pathEditor; setPathEditor(undefined); if (target.side === 'local') void loadLocal(target.value.trim()); else void loadRemote(target.value.trim()); };
  const openCopy = (source: FileEntry) => { if (!peers.length) { onError('没有其他已连接服务器可作为目标。'); return; } setCopyDraft({ source, peerId: peers[0].server.id, destPath: source.path }); };
  const submitCopy = () => { if (!copyDraft) return; const peer = peers.find((item) => item.server.id === copyDraft.peerId); if (!peer || !copyDraft.destPath.trim()) return; const request: Extract<PendingTransfer, { kind: 'serverToServer' }> = { kind: 'serverToServer', sourceServerId: server.id, sourceConnectionId: connection.id, sourcePath: copyDraft.source.path, destServerId: peer.server.id, destConnectionId: peer.connection.id, destPath: copyDraft.destPath.trim() }; setCopyDraft(undefined); void startServerCopy(request); };

  const scopedTransfers = useMemo(() => transfers.filter((job) => job.connectionId === connection.id || job.sourceConnectionId === connection.id), [connection.id, transfers]);
  const visibleTransfers = useMemo(() => scopedTransfers.filter((job) => queueFilter === 'active' ? ['queued', 'running', 'paused'].includes(job.state) : queueFilter === 'completed' ? job.state === 'completed' : ['failed', 'cancelled'].includes(job.state)), [queueFilter, scopedTransfers]);
  const activeCount = scopedTransfers.filter((item) => ['queued', 'running', 'paused'].includes(item.state)).length;
  const selectedLocal = selected?.side === 'local' ? localEntries.find((item) => item.path === selected.path) : undefined;
  const selectedRemote = selected?.side === 'remote' ? remoteEntries.find((item) => item.path === selected.path) : undefined;
  const selectedLocalFiles = localEntries.filter((item) => item.kind === 'file' && selectedPaths.local.includes(item.path));
  const selectedRemoteFiles = remoteEntries.filter((item) => item.kind === 'file' && selectedPaths.remote.includes(item.path));
  const localRows = localEntries.map((entry) => <div key={entry.path} className={`dual-file-row ${selected?.side === 'local' && selected.path === entry.path ? 'selected' : ''}`} tabIndex={0} role="button" onKeyDown={(event) => { if (event.key === 'Enter' && entry.kind === 'directory') void loadLocal(entry.path); }} draggable={entry.kind === 'file'} onDragStart={(event) => beginDrag(event, { side: 'local', entry })} onClick={() => { setSelected({ side: 'local', path: entry.path }); setSelectedPaths((items) => ({ ...items, local: [entry.path] })); }} onDoubleClick={() => entry.kind === 'directory' && void loadLocal(entry.path)} onDragOver={(event) => entry.kind === 'directory' && event.preventDefault()} onDrop={(event) => entry.kind === 'directory' && dropLocal(event, entry.path)}><input className="file-select" type="checkbox" aria-label={`选择 ${entry.name}`} checked={selectedPaths.local.includes(entry.path)} onClick={(event) => event.stopPropagation()} onChange={(event) => toggleSelection('local', entry.path, event.target.checked)} /><input className="file-select" type="checkbox" aria-label={`选择 ${entry.name}`} checked={selectedPaths.remote.includes(entry.path)} onClick={(event) => event.stopPropagation()} onChange={(event) => toggleSelection('remote', entry.path, event.target.checked)} /><span className={`entry-icon ${entry.kind}`}>{entry.kind === 'directory' ? '■' : '▧'}</span><strong>{entry.name}</strong><span>{formatSize(entry.size)}</span><span>{formatDate(entry.modifiedAt)}</span><span>本地</span></div>);
  const remoteRows = remoteEntries.map((entry) => <div key={entry.path} className={`dual-file-row ${selected?.side === 'remote' && selected.path === entry.path ? 'selected' : ''}`} tabIndex={0} role="button" onKeyDown={(event) => { if (event.key === 'Enter' && entry.kind === 'directory') void loadRemote(entry.path); }} draggable={entry.kind === 'file'} onDragStart={(event) => beginDrag(event, { side: 'remote', entry })} onClick={() => { setSelected({ side: 'remote', path: entry.path }); setSelectedPaths((items) => ({ ...items, remote: [entry.path] })); }} onDoubleClick={() => entry.kind === 'directory' && void loadRemote(entry.path)} onDragOver={(event) => entry.kind === 'directory' && event.preventDefault()} onDrop={(event) => entry.kind === 'directory' && dropRemote(event, entry.path)}><span className={`entry-icon ${entry.kind}`}>{entry.kind === 'directory' ? '■' : '▧'}</span><strong>{entry.name}</strong><span>{formatSize(entry.size)}</span><span>{formatDate(entry.modifiedAt)}</span><span>{entry.mode || '—'}</span><div className="row-menu">{entry.kind === 'file' && <button onClick={(event) => { event.stopPropagation(); void startTransfer('download', localJoin(localPath, entry.name), entry.path); }}>下载</button>}{entry.kind === 'file' && peers.length > 0 && <button onClick={(event) => { event.stopPropagation(); openCopy(entry); }}>复制</button>}<button className="danger" onClick={(event) => { event.stopPropagation(); setDeleteTarget(entry); }}>删除</button></div></div>);

  return <section className="files-view dual-files-view">
    <div className="dual-file-panes" style={{ '--local-pane': `${localPanePercent}%` } as CSSProperties}>
      <section className={dropSide === 'local' ? 'file-pane drop-active' : 'file-pane'} onDragOver={(event) => { if (Array.from(event.dataTransfer.types).includes(DRAG_TYPE)) { event.preventDefault(); setDropSide('local'); } }} onDragLeave={() => setDropSide(undefined)} onDrop={(event) => { setDropSide(undefined); dropLocal(event); }}><header className="file-pane-title"><b>本地文件</b><span>{localEntries.length} 项{selectedLocalFiles.length ? ` · 已选 ${selectedLocalFiles.length}` : ''}</span></header><div className="file-pane-controls"><button title="上一级" aria-label="本地上一级" onClick={() => void loadLocal(parentPath(localPath))}>←</button><button title="刷新" aria-label="刷新本地目录" disabled={localLoading} onClick={() => void loadLocal(localPath)}>↻</button><button className="path-field" title={localPath} onClick={() => setPathEditor({ side: 'local', value: localPath })}>{localPath || '本地目录'}</button><button className="transfer-primary" disabled={!selectedLocalFiles.length} onClick={() => void startBatch('upload', selectedLocalFiles)}>↑ 上传 {selectedLocalFiles.length || ''}</button></div><div className="dual-file-header"><span>名称</span><span>大小</span><span>修改时间</span><span>位置</span></div><div className="dual-file-list">{localRows}{localLoading && !localEntries.length && <div className="file-empty">正在加载本地目录…</div>}{localError && <div className="file-empty file-load-error"><span>{localError}</span><button onClick={() => void loadLocal(localPath)}>重试</button></div>}{!localLoading && !localError && !localEntries.length && <div className="file-empty">空目录</div>}</div></section>
      <div className="file-pane-splitter" onPointerDown={resizePanes}><span>⇄</span></div>
      <section className={dropSide === 'remote' ? 'file-pane drop-active' : 'file-pane'} onDragOver={(event) => { if (Array.from(event.dataTransfer.types).includes(DRAG_TYPE)) { event.preventDefault(); setDropSide('remote'); } }} onDragLeave={() => setDropSide(undefined)} onDrop={(event) => { setDropSide(undefined); dropRemote(event); }}><header className="file-pane-title"><b>远程文件</b><span className="server-chip"><i />{server.name}</span></header><div className="file-pane-controls"><button title="上一级" aria-label="远程上一级" onClick={() => void loadRemote(parentPath(remotePath, true))}>←</button><button title="刷新" aria-label="刷新远程目录" disabled={remoteLoading} onClick={() => void loadRemote(remotePath)}>↻</button><button className="path-field" title={remotePath} onClick={() => setPathEditor({ side: 'remote', value: remotePath })}>{remotePath}</button><button className="transfer-primary" disabled={!selectedRemoteFiles.length} onClick={() => void startBatch('download', selectedRemoteFiles)}>↓ 下载 {selectedRemoteFiles.length || ''}</button><button onClick={() => setDirectoryName('')}>＋ 新建目录</button></div><div className="dual-file-header"><span>名称</span><span>大小</span><span>修改时间</span><span>权限</span></div><div className="dual-file-list">{remoteRows}{remoteLoading && !remoteEntries.length && <div className="file-empty">正在加载远程目录…</div>}{remoteError && <div className="file-empty file-load-error"><span>{remoteError}</span><button onClick={() => void loadRemote(remotePath)}>重试</button></div>}{!remoteLoading && !remoteError && !remoteEntries.length && <div className="file-empty">空目录</div>}</div></section>
    </div>
    <section className={`transfer-queue ${queueCollapsed ? 'collapsed' : ''}`}><header><button className="queue-collapse" aria-label={queueCollapsed ? '展开传输队列' : '收起传输队列'} onClick={() => setQueueCollapsed((value) => !value)}>{queueCollapsed ? '⌃' : '⌄'}</button><b>传输队列</b><button className={queueFilter === 'active' ? 'active' : ''} onClick={() => setQueueFilter('active')}>进行中 {activeCount}</button><button className={queueFilter === 'completed' ? 'active' : ''} onClick={() => setQueueFilter('completed')}>成功</button><button className={queueFilter === 'failed' ? 'active' : ''} onClick={() => setQueueFilter('failed')}>异常</button><span /><button onClick={() => void clearFinished()}>清除已结束</button></header>{!queueCollapsed && <><div className="transfer-table-head"><span>方向</span><span>本地路径</span><span>远程路径</span><span>大小</span><span>进度</span><span>速度</span><span>状态 / 剩余</span><span>操作</span></div><div className="transfer-table-body">{visibleTransfers.map((job) => { const percent = Math.min(100, Math.round(job.transferredBytes / (job.totalBytes || 1) * 100)); const showDetail = errorDetailId === job.transferId; return <div key={job.transferId}><div className="transfer-table-row"><span className="transfer-direction" title={job.kind === 'upload' ? '上传' : job.kind === 'download' ? '下载' : '跨服务器复制'}>{job.kind === 'upload' ? '↑' : job.kind === 'download' ? '↓' : '⇄'}</span><span title={job.localPath}>{job.kind === 'serverToServer' ? job.sourcePath || '—' : job.localPath}</span><span title={job.remotePath}>{job.remotePath}</span><span>{formatSize(job.totalBytes)}</span><span className="queue-progress"><progress max={100} value={percent} /><small>{percent}%</small></span><span>{formatSpeed(job.speedBytesPerSec)}</span><span className={`queue-state ${job.state}`}><b>{stateLabel(job.state)}</b><small>{formatEta(job)}</small></span><span className="queue-actions">{job.state === 'running' && <button title="暂停" onClick={() => void api.fsTransferPause(job.transferId)}>Ⅱ</button>}{job.state === 'paused' && <button title="继续" onClick={() => void api.fsTransferResume(job.transferId)}>▶</button>}{['running', 'paused'].includes(job.state) && <button title="取消" onClick={() => void api.fsTransferCancel(job.transferId)}>×</button>}{job.state === 'failed' && <button onClick={() => retry(job)}>重试</button>}{job.state === 'failed' && <button onClick={() => setErrorDetailId(showDetail ? undefined : job.transferId)}>详情</button>}</span></div>{showDetail && job.error && <div className="transfer-error">{job.error.code}：{job.error.message}</div>}</div>; })}{!visibleTransfers.length && <div className="queue-empty">暂无传输任务</div>}</div></>}</section>
    {conflict && <div className="modal-backdrop" role="presentation" onClick={() => setConflict(undefined)}><section className="modal transfer-dialog" role="dialog" aria-modal="true" aria-labelledby="transfer-conflict-title" onClick={(event) => event.stopPropagation()}><div className="modal-titlebar"><div><p className="eyebrow">需要确认</p><h3 id="transfer-conflict-title">目标文件已存在</h3></div><button className="modal-close" aria-label="关闭" onClick={() => setConflict(undefined)}>×</button></div><div className="transfer-dialog-body"><p>继续传输将替换已有文件。请确认目标路径和操作。</p><code>{conflict.kind === 'serverToServer' ? conflict.destPath : conflict.kind === 'upload' ? conflict.remotePath : conflict.localPath}</code></div><div className="modal-footer"><button className="small-button" onClick={() => setConflict(undefined)}>取消</button><button className="primary-button danger-button" onClick={() => resolveConflict(true)}>覆盖并继续</button></div></section></div>}
    {copyDraft && <div className="modal-backdrop" role="presentation" onClick={() => setCopyDraft(undefined)}><section className="modal transfer-dialog" role="dialog" aria-modal="true" aria-labelledby="copy-server-title" onClick={(event) => event.stopPropagation()}><div className="modal-titlebar"><div><p className="eyebrow">跨服务器复制</p><h3 id="copy-server-title">选择目标服务器</h3></div><button className="modal-close" aria-label="关闭" onClick={() => setCopyDraft(undefined)}>×</button></div><div className="transfer-dialog-body"><label>源文件 <code>{copyDraft.source.path}</code></label><label>目标服务器<select value={copyDraft.peerId} onChange={(event) => setCopyDraft({ ...copyDraft, peerId: event.target.value })}>{peers.map((peer) => <option key={peer.server.id} value={peer.server.id}>{peer.server.name}</option>)}</select></label><label>目标路径<input value={copyDraft.destPath} onChange={(event) => setCopyDraft({ ...copyDraft, destPath: event.target.value })} /></label></div><div className="modal-footer"><button className="small-button" onClick={() => setCopyDraft(undefined)}>取消</button><button className="primary-button" onClick={submitCopy}>开始复制</button></div></section></div>}
    {pathEditor && <div className="modal-backdrop" role="presentation" onClick={() => setPathEditor(undefined)}><section className="modal transfer-dialog" role="dialog" aria-modal="true" aria-labelledby="path-editor-title" onClick={(event) => event.stopPropagation()}><div className="modal-titlebar"><div><p className="eyebrow">目录导航</p><h3 id="path-editor-title">前往路径</h3></div><button className="modal-close" aria-label="关闭" onClick={() => setPathEditor(undefined)}>×</button></div><form className="transfer-dialog-body" onSubmit={(event) => { event.preventDefault(); savePath(); }}><label>路径<input autoFocus value={pathEditor.value} onChange={(event) => setPathEditor({ ...pathEditor, value: event.target.value })} /></label><div className="modal-footer"><button className="small-button" type="button" onClick={() => setPathEditor(undefined)}>取消</button><button className="primary-button" type="submit">前往</button></div></form></section></div>}
    {directoryName !== undefined && <div className="modal-backdrop" role="presentation" onClick={() => setDirectoryName(undefined)}><section className="modal transfer-dialog" role="dialog" aria-modal="true" aria-labelledby="mkdir-title" onClick={(event) => event.stopPropagation()}><div className="modal-titlebar"><div><p className="eyebrow">远程文件</p><h3 id="mkdir-title">新建目录</h3></div><button className="modal-close" aria-label="关闭" onClick={() => setDirectoryName(undefined)}>×</button></div><form className="transfer-dialog-body" onSubmit={(event) => { event.preventDefault(); void mkdir(); }}><label>目录名<input autoFocus value={directoryName} onChange={(event) => setDirectoryName(event.target.value)} /></label><div className="modal-footer"><button className="small-button" type="button" onClick={() => setDirectoryName(undefined)}>取消</button><button className="primary-button" type="submit">新建目录</button></div></form></section></div>}
    {deleteTarget && <div className="modal-backdrop" role="presentation" onClick={() => setDeleteTarget(undefined)}><section className="modal transfer-dialog" role="dialog" aria-modal="true" aria-labelledby="delete-file-title" onClick={(event) => event.stopPropagation()}><div className="modal-titlebar"><div><p className="eyebrow">危险操作</p><h3 id="delete-file-title">确认删除</h3></div><button className="modal-close" aria-label="关闭" onClick={() => setDeleteTarget(undefined)}>×</button></div><div className="transfer-dialog-body"><p>删除后无法恢复；目录会递归删除其内容。</p><code>{deleteTarget.path}</code></div><div className="modal-footer"><button className="small-button" onClick={() => setDeleteTarget(undefined)}>取消</button><button className="primary-button danger-button" onClick={() => void removeRemote()}>删除</button></div></section></div>}
  </section>;
}
